# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CryptoCode', models.CharField(max_length=10)),
                ('CryptoName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curPrice', models.FloatField(max_length=10)),
                ('prevPrice', models.FloatField(max_length=10)),
                ('inBTC', models.FloatField(max_length=10)),
                ('CryptoCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crawler.CryptoCurrency')),
            ],
        ),
    ]
